	pipeline{
	
			agent any
				Stages{
					Stage('Build')
						{
							Steps{	
								echo "build"
								}
						}
					
					Stage('Test')
						{
							Steps{	
								echo "test"
								 }
						}
					}
					
					Stage('Test')
						{
							Steps{	
								echo "test"
								 }
						}
					}
					
	}